-- AUTO-GENERATED from cheatsheet.html (do not hand-edit; regenerate to keep parity).
-- Flat list of cheatsheet entries used by the in-nvim reader + Telescope picker.
-- Fields: category, keys, desc, mode ('n'/'i'/'v'/'x'/'o'/'c'/'t'/'tmux'), warn.
return {
  { category = 'Vim · Motions', keys = 'h j k l', desc = 'Left / down / up / right', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'w  b  e', desc = 'Next word start / back word / end of word', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'W  B  E', desc = 'Same, but WORD (whitespace-delimited)', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = '0  ^  $', desc = 'Line start / first non-blank / line end', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'gg  G', desc = 'Top of file / bottom of file', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = '{n}G', desc = 'Jump to line n (e.g. 42G)', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = '{  }', desc = 'Previous / next paragraph', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'C-u  C-d', desc = 'Scroll half page up / down', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'C-b  C-f', desc = 'Scroll full page up / down', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'H  M  L', desc = 'Top / middle / bottom of screen', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = '%', desc = 'Jump to matching bracket', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'f{c}  F{c}', desc = 'Find char forward / backward on line', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 't{c}  T{c}', desc = 'Till (before) char forward / backward', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = ';  ,', desc = 'Repeat / reverse last f t F T', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = '*  #', desc = 'Search word under cursor forward / backward', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = '`` ', desc = 'Jump back to position before last jump', mode = 'n', warn = false },
  { category = 'Vim · Motions', keys = 'C-o  C-i', desc = 'Older / newer position in jumplist', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'i  a', desc = 'Insert before cursor / append after', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'I  A', desc = 'Insert at line start / append at line end', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'o  O', desc = 'Open new line below / above', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'x  X', desc = 'Delete char under / before cursor', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'r{c}  R', desc = 'Replace one char / replace mode', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'dd  yy', desc = 'Delete line / yank line', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'p  P', desc = 'Paste after / before cursor', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'dw  cw', desc = 'Delete / change word', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'D  C', desc = 'Delete / change to end of line', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = '>>  <<', desc = 'Indent / outdent line', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'J', desc = 'Join line below into current', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'gU{m}  gu{m}', desc = 'Uppercase / lowercase over motion', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = '~', desc = 'Toggle case of char', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = 'u  C-r', desc = 'Undo / redo', mode = 'n', warn = false },
  { category = 'Vim · Editing', keys = '.', desc = 'Repeat last change', mode = 'n', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'd c y {motion}', desc = 'Delete / change / yank over a motion', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'iw  aw', desc = 'Inner word / a word (with surrounding space)', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'i"  a"', desc = 'Inside / around quotes', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'ip  ap', desc = 'Inner / a paragraph', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'i(  i{  i[', desc = 'Inside brackets / braces / squares', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'ci"  ci(', desc = 'Change inside quotes / parens', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'di{  ya(', desc = 'Delete inside braces / yank around parens', mode = 'o', warn = false },
  { category = 'Vim · Operators + Text Objects', keys = 'ih', desc = 'Select git hunk (via gitsigns)', mode = 'o', warn = false },
  { category = 'Vim · Visual', keys = 'v  V  C-v', desc = 'Visual char / line / block', mode = 'n', warn = false },
  { category = 'Vim · Visual', keys = 'o', desc = 'Move to other end of selection', mode = 'v', warn = false },
  { category = 'Vim · Visual', keys = 'gv', desc = 'Reselect last visual selection', mode = 'n', warn = false },
  { category = 'Vim · Visual', keys = '>  <', desc = 'Indent / outdent selection', mode = 'v', warn = false },
  { category = 'Vim · Visual', keys = 'y  d  c', desc = 'Yank / delete / change selection', mode = 'v', warn = false },
  { category = 'Vim · Visual', keys = 'u  U', desc = 'Lowercase / uppercase selection', mode = 'v', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = '/{pat}  ?{pat}', desc = 'Search forward / backward', mode = 'n', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = 'n  N', desc = 'Next / previous match', mode = 'n', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = ':%s/old/new/g', desc = 'Replace all in file', mode = 'c', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = ':s/old/new/g', desc = 'Replace all in current line', mode = 'c', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = '"{r}y  "{r}p', desc = 'Yank to / paste from register r', mode = 'n', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = 'q{r} … q', desc = 'Record macro to register r (q to stop)', mode = 'n', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = '@{r}  @@', desc = 'Play macro r / replay last macro', mode = 'n', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = 'ma  `a', desc = 'Set mark a / jump to mark a', mode = 'n', warn = false },
  { category = 'Vim · Search, Replace & Registers', keys = 'za  zR  zM', desc = 'Toggle fold / open all / close all', mode = 'n', warn = false },
  { category = 'Nvim · General (your keymaps)', keys = 'jk', desc = 'Exit insert mode (instead of Esc)', mode = 'i', warn = false },
  { category = 'Nvim · General (your keymaps)', keys = '<leader>nh', desc = 'Clear search highlights', mode = 'n', warn = false },
  { category = 'Nvim · General (your keymaps)', keys = '<leader>+  <leader>-', desc = 'Increment / decrement number under cursor', mode = 'n', warn = false },
  { category = 'Nvim · General (your keymaps)', keys = 'j  k', desc = 'Move by display line when wrapped (gj/gk)', mode = 'n', warn = false },
  { category = 'Nvim · General (your keymaps)', keys = 'K', desc = 'Show hover documentation (LSP)', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>sv', desc = 'Split window vertically', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>sh', desc = 'Split horizontally — ⚠ overridden by Telescope \'Search Help\'', mode = 'n', warn = true },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>se', desc = 'Make splits equal size', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>sx', desc = 'Close current split', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = 'C-h C-j C-k C-l', desc = 'Move between splits & tmux panes (tmux-navigator)', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>to', desc = 'Open new tab', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>tx', desc = 'Close current tab', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>tn  <leader>tp', desc = 'Next / previous tab', mode = 'n', warn = false },
  { category = 'Nvim · Windows, Splits & Tabs', keys = '<leader>tf', desc = 'Open current buffer in a new tab', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = 'gd', desc = 'Go to definition (Telescope)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = 'gD', desc = 'Go to declaration', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = 'gr', desc = 'Show references (Telescope)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = 'gI', desc = 'Go to implementation (Telescope)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = 'gt', desc = 'Go to type definition (Telescope)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = 'K', desc = 'Hover documentation', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>ca', desc = 'Code action (works on visual selection too)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>rn', desc = 'Smart rename symbol', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>rs', desc = 'Restart LSP', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>D', desc = 'Buffer diagnostics (Telescope)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>d', desc = 'Line diagnostics (float)', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '[d  ]d', desc = 'Previous / next diagnostic', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>e', desc = 'Open floating diagnostic', mode = 'n', warn = false },
  { category = 'Nvim · LSP (on attach)', keys = '<leader>q', desc = 'Diagnostics to location list', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sf', desc = 'Search files (find_files)', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sg', desc = 'Search by grep (live_grep)', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sG', desc = 'Live grep on git root', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sw', desc = 'Search current word under cursor', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sh', desc = 'Search help tags', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sd', desc = 'Search diagnostics', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>sr', desc = 'Resume last picker', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>ss', desc = 'Select a Telescope builtin', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>st', desc = 'Search TODOs', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>gf', desc = 'Search git files', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>?', desc = 'Find recently opened files', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader><space>', desc = 'Find existing buffers', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>/', desc = 'Fuzzy search in current buffer', mode = 'n', warn = false },
  { category = 'Nvim · Telescope (find & search)', keys = '<leader>s/', desc = 'Live grep in open files', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>lg', desc = 'Open LazyGit', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hs', desc = 'Stage hunk (also works on visual range)', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hr', desc = 'Reset hunk (also works on visual range)', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hS', desc = 'Stage entire buffer', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hR', desc = 'Reset entire buffer', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hu', desc = 'Undo stage hunk', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hp', desc = 'Preview hunk', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hb', desc = 'Blame current line (full)', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hB', desc = 'Toggle inline line blame', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hd', desc = 'Diff this', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = '<leader>hD', desc = 'Diff this against ~', mode = 'n', warn = false },
  { category = 'Nvim · Git (gitsigns + lazygit)', keys = 'ih', desc = 'Text object: select hunk (in d/c/y or visual)', mode = 'o', warn = false },
  { category = 'Nvim · Flash (jump)', keys = 's', desc = 'Flash jump to any location', mode = 'n', warn = false },
  { category = 'Nvim · Flash (jump)', keys = 'S', desc = 'Flash Treesitter (select nodes)', mode = 'n', warn = false },
  { category = 'Nvim · Flash (jump)', keys = 'r', desc = 'Remote Flash (operator-pending)', mode = 'o', warn = false },
  { category = 'Nvim · Flash (jump)', keys = 'R', desc = 'Treesitter search', mode = 'o', warn = false },
  { category = 'Nvim · Flash (jump)', keys = 'C-s', desc = 'Toggle Flash while in search', mode = 'c', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = '-', desc = 'Open parent directory as editable buffer', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = '<CR>', desc = 'Open file / enter directory', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'C-s', desc = 'Open under cursor in vertical split', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'C-h', desc = 'Open under cursor in horizontal split', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'C-t', desc = 'Open under cursor in new tab', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'C-p', desc = 'Preview under cursor', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'C-l', desc = 'Refresh listing', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'C-c', desc = 'Close oil', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = '_', desc = 'Open current working directory', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = '`  ~', desc = 'cd to dir / cd (tab scope)', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'gs', desc = 'Change sort order', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'gx', desc = 'Open in external program', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'g.', desc = 'Toggle hidden files', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'g\\', desc = 'Toggle trash view', mode = 'n', warn = false },
  { category = 'Nvim · Oil (file explorer)', keys = 'g?', desc = 'Show oil help', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xx', desc = 'Diagnostics (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xX', desc = 'Buffer diagnostics (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xs', desc = 'Symbols (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xl', desc = 'LSP definitions / references (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xL', desc = 'Location list (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xq', desc = 'Quickfix list (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = '<leader>xt', desc = 'TODOs (Trouble)', mode = 'n', warn = false },
  { category = 'Nvim · Trouble & TODOs', keys = ']t  [t', desc = 'Next / previous TODO comment', mode = 'n', warn = false },
  { category = 'Nvim · Terminal (toggleterm)', keys = 'C-t', desc = 'Toggle floating terminal', mode = 'n', warn = false },
  { category = 'Nvim · Terminal (toggleterm)', keys = 'C-t', desc = 'Toggle terminal (also closes it from inside)', mode = 't', warn = false },
  { category = 'Nvim · Terminal (toggleterm)', keys = 'C-\\ C-n', desc = 'Exit terminal mode to normal mode', mode = 't', warn = false },
  { category = 'Tmux · Navigation (tmux-navigator)', keys = 'C-h C-j C-k C-l', desc = 'Move between panes AND vim splits seamlessly', mode = 'tmux', warn = false },
  { category = 'Tmux · Navigation (tmux-navigator)', keys = 'C-\\', desc = 'Move to previously active pane / split', mode = 'tmux', warn = false },
  { category = 'Tmux · Sessions (resurrect + continuum)', keys = 'prefix C-s', desc = 'Save tmux environment (resurrect)', mode = 'tmux', warn = false },
  { category = 'Tmux · Sessions (resurrect + continuum)', keys = 'prefix C-r', desc = 'Restore saved environment (resurrect)', mode = 'tmux', warn = false },
  { category = 'Tmux · Sessions (resurrect + continuum)', keys = '(automatic)', desc = 'Continuum auto-saves & restores on start — no keybind', mode = 'tmux', warn = false },
  { category = 'Tmux · Plugins (tpm)', keys = 'prefix I', desc = 'Install plugins listed in tmux.conf', mode = 'tmux', warn = false },
  { category = 'Tmux · Plugins (tpm)', keys = 'prefix U', desc = 'Update plugins', mode = 'tmux', warn = false },
  { category = 'Tmux · Plugins (tpm)', keys = 'prefix Alt-u', desc = 'Remove/uninstall plugins not on the list', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix c', desc = 'Create new window', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix ,', desc = 'Rename current window', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix n  prefix p', desc = 'Next / previous window', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix 0-9', desc = 'Jump to window by number', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix w', desc = 'Choose window from list', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix %', desc = 'Split pane vertically', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix "', desc = 'Split pane horizontally', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix o', desc = 'Cycle through panes', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix z', desc = 'Zoom / unzoom current pane', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix x', desc = 'Kill current pane', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix {  prefix }', desc = 'Swap pane left / right', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix Space', desc = 'Cycle pane layouts', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix d', desc = 'Detach from session', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix [', desc = 'Enter copy/scroll mode (q to exit)', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix ]', desc = 'Paste buffer', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix :', desc = 'Command prompt', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix ?', desc = 'List all key bindings', mode = 'tmux', warn = false },
  { category = 'Tmux · Windows & Panes (defaults)', keys = 'prefix t', desc = 'Show clock', mode = 'tmux', warn = false },
}
